### PR TITLE
Finder Label Support

### PR DESCRIPTION
**Pull request by songchenwen**
Add Finder label support. Resolved benjaminoakes/maid#125

- `tags(path)` to get tags from a file
- `has_tags?(path)` to tell if a file has any tags
- `contains_tag?(path, tag)` to tell if a file has a certain tag
- `add_tag(path, tag)` to add a tag or a list of tags to a file
- `remove_tag(path, tag)` to remove a tag or a list of tags from a file
- `set_tag(path, tag)` to set a tag or a list of tags to a file

### CODE REVIEW

**Comment by songchenwen** [comment]
If there's anything wrong please let me know.

**Comment by benjaminoakes** [comment]
This is great stuff!  Thank you so much for taking the effort to do this.  Merging now...

**Comment by benjaminoakes** [comment]
I've released an alpha build based on this pull request.  I'd appreciate any help with testing!

https://rubygems.org/gems/maid/versions/0.8.0.alpha.1

**Comment by songchenwen** [comment]
I've ran `gem install maid --pre` to install 0.8.0.alpha.1.

I saw `maid (0.8.0.alpha.1, 0.7.0, 0.6.1)` when `gem list`

But I still get `0.7.0` when `maid version`. Any further steps to use the alpha version by default?

**Comment by mistercorea** [comment]
I am trying to use but I am getting an error with `block (3 levels) in <top (required)>': undefined method `add_tag' for #<Maid::Maid:0x00007ff6a222c590> (NoMethodError)`

**Pull request merged**
